//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonConEntrega.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddonConEntrega.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;20200404&quot; FormType=&quot;20200404&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Aprobacion Intereses&quot; visible=&quot;1&quot; default_button=&quot;btnProc&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;1325&quot; height=&quot;492&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_FACT&quot;&gt;
        ///              &lt;Columns&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmAutorizacionInteres {
            get {
                return ResourceManager.GetString("frmAutorizacionInteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconoModulo {
            get {
                object obj = ResourceManager.GetObject("IconoModulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;Menus&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;!--&lt;Menu Checked=&quot;0&quot; Enabled=&quot;1&quot; FatherUID=&quot;2048&quot; Position=&quot;4&quot; String=&quot;Conf. Intereses Moratorios&quot; Type=&quot;1&quot; UniqueID=&quot;AUTINT&quot;/&gt;--&gt;
        ///    &lt;/action&gt;
        ///  &lt;/Menus&gt;
        ///&lt;/Application&gt;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXX_CON_ENT.
        /// </summary>
        internal static string NombreAddon {
            get {
                return ResourceManager.GetString("NombreAddon", resourceCulture);
            }
        }
    }
}
